version: '3.8'
services:
  videogames:
    image: mysql:8
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: videogames
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - BRIEF8

networks:
  BRIEF8:
    external: true
